### ISSUE TITLE
[PE-D][Tester F] Not enough visual aid in User guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T15-1/tp#130]
![image.png](https://raw.githubusercontent.com/wendy0107/ped/main/files/8c1fcedc-a8bb-42f1-9d5c-58eb20480633.png)

User guide only has one image under quick start while other features do not have any images to aid users at all.
It would be helpful to add more visual aids.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: wendy0107/ped#2

**Comment by Zeli0** [comment]
This has been resolved in #217.
