### ISSUE TITLE
[PE-D][Tester D] Incorrect command format in edit mode error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T15-1/tp#144]
While in edit view to edit the inventory of a character, entering `inventory` prints the error message from AB3 which mentions NAME, PHONE, EMAIL and ADDRESS, which are not valid fields in Reroll entities.

![image.png](https://raw.githubusercontent.com/nramapurath/ped/main/files/0ce60802-ac10-42d9-85f2-e3ba9f2214ff.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: nramapurath/ped#3

**Comment by Zeli0** [comment]
This is the same bug mentioned in the latter half of #171
