### ISSUE TITLE
[PE-D][Tester C] Message shows "Exited Edit Mode" after exiting view mode

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T15-1/tp#162]
After entering view mode:

![image.png](https://raw.githubusercontent.com/noahxinjie/ped/main/files/b84440d6-4ce2-4f6c-9356-72ab76196902.png)

And exiting said view mode:

![image.png](https://raw.githubusercontent.com/noahxinjie/ped/main/files/730f2eb9-0537-4dd8-8377-76116bbec118.png)

It says that we have "Exited Edit Mode".
Perhaps the message can be customised to "Exited View Mode" instead.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: noahxinjie/ped#7

**Comment by LeonardYam** [comment]
Feature deleted
